# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mygui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 517)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.sizeSlider = QtWidgets.QSlider(self.centralWidget)
        self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sizeSlider.setObjectName("sizeSlider")
        self.horizontalLayout_3.addWidget(self.sizeSlider)
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.opacitySlider = QtWidgets.QSlider(self.centralWidget)
        self.opacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider.setObjectName("opacitySlider")
        self.horizontalLayout_3.addWidget(self.opacitySlider)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_3.addWidget(self.line_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settingsButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.settingsButton.setFont(font)
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout_3.addWidget(self.settingsButton)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_3.addWidget(self.line_6)
        self.ViewProb = QtWidgets.QLabel(self.centralWidget)
        self.ViewProb.setObjectName("ViewProb")
        self.horizontalLayout_3.addWidget(self.ViewProb)
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox.setMaxVisibleItems(17)
        self.comboBox.setMaxCount(2147483646)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.runButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMinimumSize(QtCore.QSize(60, 30))
        self.runButton.setMaximumSize(QtCore.QSize(60, 30))
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.binarisationCheckBox = QtWidgets.QCheckBox(self.widget)
        self.binarisationCheckBox.setObjectName("binarisationCheckBox")
        self.gridLayout.addWidget(self.binarisationCheckBox, 12, 0, 1, 1)
        self.autoRunButton = QtWidgets.QRadioButton(self.widget)
        self.autoRunButton.setObjectName("autoRunButton")
        self.gridLayout.addWidget(self.autoRunButton, 4, 0, 1, 1)
        self.eraserButton = QtWidgets.QPushButton(self.widget)
        self.eraserButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eraserButton.sizePolicy().hasHeightForWidth())
        self.eraserButton.setSizePolicy(sizePolicy)
        self.eraserButton.setMinimumSize(QtCore.QSize(60, 30))
        self.eraserButton.setMaximumSize(QtCore.QSize(60, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/images/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraserButton.setIcon(icon)
        self.eraserButton.setCheckable(True)
        self.eraserButton.setObjectName("eraserButton")
        self.gridLayout.addWidget(self.eraserButton, 1, 0, 1, 1)
        self.brushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brushButton.sizePolicy().hasHeightForWidth())
        self.brushButton.setSizePolicy(sizePolicy)
        self.brushButton.setMinimumSize(QtCore.QSize(60, 30))
        self.brushButton.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.brushButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Downloads/images/paint-brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brushButton.setIcon(icon1)
        self.brushButton.setCheckable(True)
        self.brushButton.setObjectName("brushButton")
        self.gridLayout.addWidget(self.brushButton, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 7, 0, 1, 1)
        self.overwriteCheckBox = QtWidgets.QCheckBox(self.widget)
        self.overwriteCheckBox.setObjectName("overwriteCheckBox")
        self.gridLayout.addWidget(self.overwriteCheckBox, 11, 0, 1, 1)
        self.diffusionCheckBox = QtWidgets.QCheckBox(self.widget)
        self.diffusionCheckBox.setObjectName("diffusionCheckBox")
        self.gridLayout.addWidget(self.diffusionCheckBox, 10, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(78, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(78, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.primaryButton = QtWidgets.QPushButton(self.widget_3)
        self.primaryButton.setGeometry(QtCore.QRect(0, 0, 70, 30))
        self.primaryButton.setMinimumSize(QtCore.QSize(70, 30))
        self.primaryButton.setMaximumSize(QtCore.QSize(70, 30))
        self.primaryButton.setText("")
        self.primaryButton.setObjectName("primaryButton")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(15, 0, 15, 15)
        self.gridLayout_2.setSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.colorButton_14 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_14.sizePolicy().hasHeightForWidth())
        self.colorButton_14.setSizePolicy(sizePolicy)
        self.colorButton_14.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_14.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_14.setText("")
        self.colorButton_14.setObjectName("colorButton_14")
        self.gridLayout_2.addWidget(self.colorButton_14, 0, 13, 1, 1)
        self.colorButton_10 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_10.sizePolicy().hasHeightForWidth())
        self.colorButton_10.setSizePolicy(sizePolicy)
        self.colorButton_10.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_10.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_10.setStyleSheet("")
        self.colorButton_10.setText("")
        self.colorButton_10.setObjectName("colorButton_10")
        self.gridLayout_2.addWidget(self.colorButton_10, 0, 9, 1, 1)
        self.colorButton_9 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_9.sizePolicy().hasHeightForWidth())
        self.colorButton_9.setSizePolicy(sizePolicy)
        self.colorButton_9.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_9.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_9.setStyleSheet("")
        self.colorButton_9.setText("")
        self.colorButton_9.setObjectName("colorButton_9")
        self.gridLayout_2.addWidget(self.colorButton_9, 0, 8, 1, 1)
        self.colorButton_7 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_7.sizePolicy().hasHeightForWidth())
        self.colorButton_7.setSizePolicy(sizePolicy)
        self.colorButton_7.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_7.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_7.setText("")
        self.colorButton_7.setObjectName("colorButton_7")
        self.gridLayout_2.addWidget(self.colorButton_7, 0, 6, 1, 1)
        self.colorButton_11 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_11.sizePolicy().hasHeightForWidth())
        self.colorButton_11.setSizePolicy(sizePolicy)
        self.colorButton_11.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_11.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_11.setText("")
        self.colorButton_11.setObjectName("colorButton_11")
        self.gridLayout_2.addWidget(self.colorButton_11, 0, 10, 1, 1)
        self.colorButton_13 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_13.sizePolicy().hasHeightForWidth())
        self.colorButton_13.setSizePolicy(sizePolicy)
        self.colorButton_13.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_13.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_13.setText("")
        self.colorButton_13.setObjectName("colorButton_13")
        self.gridLayout_2.addWidget(self.colorButton_13, 0, 12, 1, 1)
        self.colorButton_2 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_2.sizePolicy().hasHeightForWidth())
        self.colorButton_2.setSizePolicy(sizePolicy)
        self.colorButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_2.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_2.setStyleSheet("")
        self.colorButton_2.setText("")
        self.colorButton_2.setObjectName("colorButton_2")
        self.gridLayout_2.addWidget(self.colorButton_2, 0, 1, 1, 1)
        self.colorButton_5 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_5.sizePolicy().hasHeightForWidth())
        self.colorButton_5.setSizePolicy(sizePolicy)
        self.colorButton_5.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_5.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_5.setText("")
        self.colorButton_5.setObjectName("colorButton_5")
        self.gridLayout_2.addWidget(self.colorButton_5, 0, 4, 1, 1)
        self.colorButton_12 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_12.sizePolicy().hasHeightForWidth())
        self.colorButton_12.setSizePolicy(sizePolicy)
        self.colorButton_12.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_12.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_12.setText("")
        self.colorButton_12.setObjectName("colorButton_12")
        self.gridLayout_2.addWidget(self.colorButton_12, 0, 11, 1, 1)
        self.colorButton_4 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_4.sizePolicy().hasHeightForWidth())
        self.colorButton_4.setSizePolicy(sizePolicy)
        self.colorButton_4.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_4.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_4.setText("")
        self.colorButton_4.setObjectName("colorButton_4")
        self.gridLayout_2.addWidget(self.colorButton_4, 0, 3, 1, 1)
        self.colorButton_1 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_1.sizePolicy().hasHeightForWidth())
        self.colorButton_1.setSizePolicy(sizePolicy)
        self.colorButton_1.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_1.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_1.setStyleSheet("")
        self.colorButton_1.setText("")
        self.colorButton_1.setObjectName("colorButton_1")
        self.gridLayout_2.addWidget(self.colorButton_1, 0, 0, 1, 1)
        self.colorButton_3 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_3.sizePolicy().hasHeightForWidth())
        self.colorButton_3.setSizePolicy(sizePolicy)
        self.colorButton_3.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_3.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_3.setText("")
        self.colorButton_3.setObjectName("colorButton_3")
        self.gridLayout_2.addWidget(self.colorButton_3, 0, 2, 1, 1)
        self.colorButton_6 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_6.sizePolicy().hasHeightForWidth())
        self.colorButton_6.setSizePolicy(sizePolicy)
        self.colorButton_6.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_6.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_6.setText("")
        self.colorButton_6.setObjectName("colorButton_6")
        self.gridLayout_2.addWidget(self.colorButton_6, 0, 5, 1, 1)
        self.colorButton_8 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_8.sizePolicy().hasHeightForWidth())
        self.colorButton_8.setSizePolicy(sizePolicy)
        self.colorButton_8.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_8.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_8.setStyleSheet("")
        self.colorButton_8.setText("")
        self.colorButton_8.setObjectName("colorButton_8")
        self.gridLayout_2.addWidget(self.colorButton_8, 0, 7, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuImage = QtWidgets.QMenu(self.menuBar)
        self.menuImage.setObjectName("menuImage")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.fileToolbar = QtWidgets.QToolBar(MainWindow)
        self.fileToolbar.setIconSize(QtCore.QSize(16, 16))
        self.fileToolbar.setObjectName("fileToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolbar)
        MainWindow.insertToolBarBreak(self.fileToolbar)
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionClearImage = QtWidgets.QAction(MainWindow)
        self.actionClearImage.setObjectName("actionClearImage")
        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Downloads/images/blue-folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenImage.setIcon(icon2)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../Downloads/images/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveImage.setIcon(icon3)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionNewImage = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../Downloads/images/document-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewImage.setIcon(icon4)
        self.actionNewImage.setObjectName("actionNewImage")
        self.actionSaveLabels = QtWidgets.QAction(MainWindow)
        self.actionSaveLabels.setObjectName("actionSaveLabels")
        self.actionLoadLabels = QtWidgets.QAction(MainWindow)
        self.actionLoadLabels.setObjectName("actionLoadLabels")
        self.menuFIle.addAction(self.actionNewImage)
        self.menuFIle.addAction(self.actionOpenImage)
        self.menuFIle.addAction(self.actionLoadLabels)
        self.menuFIle.addAction(self.actionSaveImage)
        self.menuFIle.addAction(self.actionSaveLabels)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClearImage)
        self.menuImage.addSeparator()
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuImage.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.fileToolbar.addAction(self.actionLoadLabels)
        self.fileToolbar.addAction(self.actionSaveLabels)
        self.fileToolbar.addSeparator()
        self.fileToolbar.addAction(self.actionNewImage)
        self.fileToolbar.addAction(self.actionOpenImage)
        self.fileToolbar.addAction(self.actionSaveImage)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interactive Dictionary Segmention Model"))
        self.label_3.setText(_translate("MainWindow", "Brush Size"))
        self.label_2.setText(_translate("MainWindow", "Opacity"))
        self.settingsButton.setText(_translate("MainWindow", "Pre-processing settings"))
        self.ViewProb.setText(_translate("MainWindow", "View Probability Image"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.binarisationCheckBox.setText(_translate("MainWindow", "Binarisation"))
        self.autoRunButton.setText(_translate("MainWindow", "Auto Run"))
        self.eraserButton.setText(_translate("MainWindow", "Erase"))
        self.brushButton.setText(_translate("MainWindow", "Brush"))
        self.overwriteCheckBox.setText(_translate("MainWindow", "Overwrite"))
        self.diffusionCheckBox.setText(_translate("MainWindow", "2 Step Diffusion"))
        self.label.setText(_translate("MainWindow", "Options"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.fileToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionClearImage.setText(_translate("MainWindow", "Clear Image"))
        self.actionOpenImage.setText(_translate("MainWindow", "Open Image..."))
        self.actionSaveImage.setText(_translate("MainWindow", "Save Image As..."))
        self.actionNewImage.setText(_translate("MainWindow", "New Image"))
        self.actionSaveLabels.setText(_translate("MainWindow", "Save Labels As"))
        self.actionSaveLabels.setToolTip(_translate("MainWindow", "Save Labels As"))
        self.actionLoadLabels.setText(_translate("MainWindow", "Load Labels"))
        self.actionLoadLabels.setToolTip(_translate("MainWindow", "Load Labels"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

